services:
  events-api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: events-api
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - events-network

  postgres:
    image: postgres:15
    container_name: eventsmicroservice-db
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: eventsdb
    ports:
      - "5432:5432"
    volumes:
      # Persist data outside the container so that it isnt lost in case it stops or is deleted
      - pgdata:/var/lib/postgresql/data 
    networks: 
      - events-network

volumes:
  pgdata:

networks: 
  events-network:
    driver: bridge
