services:
  # ====== Users ======= #
  users-api:
    build:
      context: ./src/UsersMicroservice
      dockerfile: Dockerfile 
    container_name: users-api
    ports:
      - "5001:8080"
    depends_on:
      users-db:
        condition: service_healthy
    networks:
      - plateful-network

  users-db:
    image: postgres:15
    container_name: usersmicroservice-db
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: usersdb
    volumes:
      # Persist data outside the container so that it isnt lost in case it stops or is deleted
      - users_pgdata:/var/lib/postgresql/data 
    ports:
      - "5433:5432"
    networks: 
      - plateful-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  events-api:
    build:
      context: ./src/EventsMicroservice  
      dockerfile: Dockerfile 
    container_name: events-api
    ports:
      - "5002:8080"
    depends_on:
      events-db:
        condition: service_healthy
      users-api:
        condition: service_started
    networks:
      - plateful-network

  events-db:
    image: postgres:15
    container_name: eventsmicroservice-db
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: eventsdb
    volumes:
      # Persist data outside the container so that it isnt lost in case it stops or is deleted
      - events_pgdata:/var/lib/postgresql/data 
    ports:
      - "5434:5432"
    networks: 
      - plateful-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      users-db:
        condition: service_healthy
      events-db:
        condition: service_healthy
    networks:
      - plateful-network

volumes:
  users_pgdata:
  events_pgdata:

networks: 
  plateful-network:
    driver: bridge
