apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: events-pvc
spec:
  #Basically means that the volume can only be mounted as read/write by 1 node at a time 
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi #1GB of storage for now
