apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodclub-frontend-main
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: foodclub-frontend-main
  template:
    metadata: 
      labels:
        app: foodclub-frontend-main
    spec:
      containers:
        - name: foodclub-frontend-main
          image: ghcr.io/prvacy/foodclub-ui-next:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
