apiVersion: v1
kind: Service
metadata: 
  name: events-api
spec:
  type: NodePort # Accessible outside the cluster, unlike ClusterIP
  selector:   
    app: events-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001 # 30000â€“32767 KUBERNETES DEFAULT
