name: Events API E2E Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/EventsMicroservice/**"
  push:
    branches: ["master"]
    paths:
      - "src/EventsMicroservice/**"

jobs:
  events-api-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/EventsMicroservice/test/Events.Api.E2ETests

      - name: Build
        run: dotnet build ./src/EventsMicroservice/test/Events.Api.E2ETests --no-restore

      - name: Run E2E Tests
        run: dotnet test ./src/EventsMicroservice/test/Events.Api.E2ETests --no-build --verbosity normal #--logger "trx;LogFileName=test-results.trx"

      # Not needed for now
      # - name: Upload test results
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: test-results
      #     path: "**/TestResults/*.trx"
      #     retention-days: 7

